# @package _global_

algorithm:
  _target_: "gfn_maxent_rl.algos.path_consistency_learning.PCL"

  network: ${policy_network}

  target: null

replay:
  _target_: "gfn_maxent_rl.data.EpisodicReplayBuffer"

reward_correction: true
