# @package _global_

algorithm:
  _target_: "gfn_maxent_rl.algos.trajectory_balance.GFNTrajectoryBalance"

  network: ${policy_network}

  target: null

replay:
  _target_: "gfn_maxent_rl.data.EpisodicReplayBuffer"
